### ISSUE TITLE
This  can be used for semantic SLAM?

### ISSUE THREAD

**Issue by yejun688** [fusheng-ji/diff-gaussian-rasterization-modified#1]
RT

**Comment by fusheng-ji** [comment]
Recently, there are several awesome works like [SGS-SLAM: SEMANTIC GAUSSIAN SPLATTING FOR NEURAL DENSE SLAM](https://arxiv.org/abs/2402.03246) already applied the 3D Gaussian to semantic SLAM. I think you can reference that work to build your work, and this repo is modified from basic gaussian rasterization, so I think it can be easily expanded to your task.

**Comment by yejun688** [comment]
Thank you Reply, I will try semantic slam   :)
